name: allo
channels:
  - javascript
dependencies:
  - python=3.6
  - pip
  - cryptography
  - joblib==0.13.2
  - numpy==1.16.3
  - pandas==0.24.2 
  - scikit-learn
  - matplotlib
  - pip:
        - alpha-vantage==2.1.3
        - bcrypt==3.1.6
        - colorlover==0.3.0
        - cymysql==0.9.13
        - dash==1.0.2
        - dash-gif-component==1.0.2
        - dash-daq==0.1.0
        - dnspython==1.16.0
        - Flask-Caching==1.7.1
        - gspread==3.1.0
        - jupyterlab
        - oauth2client==4.1.3
        - plotly==4.0.0
        - pymongo==3.7.2
        - SQLAlchemy==1.3.5
        - schedule==0.6.0
        - pyportfolioopt==0.4.3
        - git+https://github.com/junyittcxt/cxt-py
