startdate: 2014-01-01 00:00:00
enddate: 2020-03-01 00:00:00
index: trpei

allocator_kwargs:
  adj_lowerbound: 0.00
  allocate_method: replicate_minimize_lookback_square_error
  strat_min_alloc: {}
  lowerbound: -0.75
  upperbound: 1.5
  sum_weight: 1.0
  constraint: 1
excluder_kwargs:
- kwargs:
    corr_threshold: 0.9
  name: exclude_high_correlation
- kwargs: {}
  name: exclude_seasonality_month
- kwargs: {}
  name: exclude_data_mined
find_filter:
  Name:
    $in:
    - SPY
    - TLT
    - GLD
  SeriesType: 
    $in:
    - yahoo
  User:
#     $in:
#     - Benchmark
    $nin:
    - Deleted

sample_population_n: 10000
sample_population_seed: 123
sample_threshold: 2
selector_kwargs:
  select_method: select_all
